cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: gisiona-lab-s3

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  cloud:
    config:
      enabled: false

server:
  port: 9090
